const initialState = [{
    category: '语种',
    categoryList: [{
        name: '华语',
        id: 0,
        isHot: true
    }, {
        name: '欧美',
        id: 1,
        isHot: false
    }, {
        name: '日语',
        id: 2,
        isHot: false
    }, {
        name: '韩语',
        id: 3,
        isHot: false
    }, {
        name: '粤语',
        id: 4,
        isHot: false
    }]
}, {
    category: '风格',
    categoryList: [{
        name: '流行',
        id: 0,
        isHot: true
    }, {
        name: '摇滚',
        id: 1,
        isHot: true
    }, {
        name: '民谣',
        id: 2,
        isHot: true
    }, {
        name: '电子',
        id: 3,
        isHot: true
    }, {
        name: '舞曲',
        id: 4,
        isHot: false
    }, {
        name: '说唱',
        id: 5,
        isHot: false
    }, {
        name: '轻音乐',
        id: 6,
        isHot: true
    }, {
        name: '爵士',
        id: 7,
        isHot: false
    }, {
        name: '乡村',
        id: 8,
        isHot: false
    }, {
        name: 'R&B/Soul',
        id: 9,
        isHot: false
    }, {
        name: '古典',
        id: 10,
        isHot: false
    }, {
        name: '民族',
        id: 11,
        isHot: false
    }, {
        name: '英伦',
        id: 12,
        isHot: false
    }, {
        name: '金属',
        id: 13,
        isHot: false
    }, {
        name: '蓝调',
        id: 14,
        isHot: false
    }, {
        name: '雷鬼',
        id: 15,
        isHot: false
    }, {
        name: '世界音乐',
        id: 16,
        isHot: false
    }, {
        name: '拉丁',
        id: 17,
        isHot: false
    }, {
        name: 'New Age',
        id: 18,
        isHot: false
    }, {
        name: '古风',
        id: 19,
        isHot: false
    }, {
        name: '后摇',
        id: 20,
        isHot: false
    }, {
        name: 'Bossa Nova',
        id: 21,
        isHot: false
    }]
}, {
    category: '场景',
    categoryList: [{
        name: '清晨',
        id: 0,
        isHot: false
    }, {
        name: '夜晚',
        id: 1,
        isHot: true
    }, {
        name: '学习',
        id: 2,
        isHot: true
    }, {
        name: '工作',
        id: 3,
        isHot: false
    }, {
        name: '午休',
        id: 4,
        isHot: false
    }, {
        name: '下午茶',
        id: 5,
        isHot: false
    }, {
        name: '地铁',
        id: 6,
        isHot: false
    }, {
        name: '驾车',
        id: 7,
        isHot: false
    }, {
        name: '运动',
        id: 8,
        isHot: true
    }, {
        name: '旅行',
        id: 9,
        isHot: false
    }, {
        name: '散步',
        id: 10,
        isHot: false
    }, {
        name: '酒吧',
        id: 11,
        isHot: false
    }]
}, {
    category: '情感',
    categoryList: [{
        name: '怀旧',
        id: 0,
        isHot: true
    }, {
        name: '清新',
        id: 1,
        isHot: true
    }, {
        name: '浪漫',
        id: 2,
        isHot: false
    }, {
        name: '治愈',
        id: 3,
        isHot: true
    }, {
        name: '放送',
        id: 4,
        isHot: false
    }, {
        name: '孤独',
        id: 5,
        isHot: false
    }, {
        name: '感动',
        id: 6,
        isHot: false
    }, {
        name: '兴奋',
        id: 7,
        isHot: false
    }, {
        name: '快乐',
        id: 8,
        isHot: true
    }, {
        name: '安静',
        id: 9,
        isHot: false
    }, {
        name: '思念',
        id: 10,
        isHot: false
    }, {
        name: '伤感',
        id: 11,
        isHot: false
    }]
}, {
    category: '主题',
    categoryList: [{
        name: '综艺',
        id: 0,
        isHot: true
    }, {
        name: '影视原声',
        id: 1,
        isHot: true
    }, {
        name: 'ACG',
        id: 2,
        isHot: true
    }, {
        name: '儿童',
        id: 3,
        isHot: false
    }, {
        name: '校园',
        id: 4,
        isHot: false
    }, {
        name: '游戏',
        id: 5,
        isHot: false
    }, {
        name: '70后',
        id: 6,
        isHot: true
    }, {
        name: '80后',
        id: 7,
        isHot: false
    }, {
        name: '90后',
        id: 8,
        isHot: false
    }, {
        name: '网络歌曲',
        id: 9,
        isHot: false
    }, {
        name: 'KTV',
        id: 10,
        isHot: false
    }, {
        name: '经典',
        id: 11,
        isHot: false
    }, {
        name: '翻唱',
        id: 12,
        isHot: false
    }, {
        name: '吉他',
        id: 13,
        isHot: false
    }, {
        name: '钢琴',
        id: 14,
        isHot: false
    }, {
        name: '乐器',
        id: 15,
        isHot: false
    }, {
        name: '榜单',
        id: 16,
        isHot: false
    }, {
        name: '00后',
        id: 17,
        isHot: false
    }]
}]
export default function songCategory(state=initialState, action) {
    return state
}